<a href="https://colab.research.google.com/github/nienhcar/Breastcancerdetection/blob/main/breastcancerdetection.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [ ]:

read_file = pd.read_excel ("/content/maindataset.xlsx")
read_file.to_csv ("breastcancer.csv", index = None,header=True)


dataset = pd.read_csv('breastcancer.csv')
X = dataset.iloc[:, 1:-1].values
y = dataset.iloc[:, -1].values

In [ ]:
print(X)

[[1.799e+01 1.038e+01 1.228e+02 ... 2.654e-01 4.601e-01 1.189e-01]
 [2.057e+01 1.777e+01 1.329e+02 ... 1.860e-01 2.750e-01 8.902e-02]
 [1.969e+01 2.125e+01 1.300e+02 ... 2.430e-01 3.613e-01 8.758e-02]
 ...
 [1.660e+01 2.808e+01 1.083e+02 ... 1.418e-01 2.218e-01 7.820e-02]
 [2.060e+01 2.933e+01 1.401e+02 ... 2.650e-01 4.087e-01 1.240e-01]
 [7.760e+00 2.454e+01 4.792e+01 ... 0.000e+00 2.871e-01 7.039e-02]]


In [ ]:
print(y)

[1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 0 1 1 1 1 1 1 1 1 0 1 0 0 0 0 0 1 1 0 1 1 0 0 0 0 1 0 1 1 0 0 0 0 1 0 1 1
 0 1 0 1 1 0 0 0 1 1 0 1 1 1 0 0 0 1 0 0 1 1 0 0 0 1 1 0 0 0 0 1 0 0 1 0 0
 0 0 0 0 0 0 1 1 1 0 1 1 0 0 0 1 1 0 1 0 1 1 0 1 1 0 0 1 0 0 1 0 0 0 0 1 0
 0 0 0 0 0 0 0 0 1 0 0 0 0 1 1 0 1 0 0 1 1 0 0 1 1 0 0 0 0 1 0 0 1 1 1 0 1
 0 1 0 0 0 1 0 0 1 1 0 1 1 1 1 0 1 1 1 0 1 0 1 0 0 1 0 1 1 1 1 0 0 1 1 0 0
 0 1 0 0 0 0 0 1 1 0 0 1 0 0 1 1 0 1 0 0 0 0 1 0 0 0 0 0 1 0 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 0 0 0 0 0 0 1 0 1 0 0 1 0 0 1 0 1 1 0 0 0 0 0 0 0 0 0 0 0 0
 0 1 0 0 1 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 1 0 1 0 0 0 0 1 1 1 0 0
 0 0 1 0 1 0 1 0 0 0 1 0 0 0 0 0 0 0 1 1 1 0 0 0 0 0 0 0 0 0 0 0 1 1 0 1 1
 1 0 1 1 0 0 0 0 0 1 0 0 0 0 0 1 0 0 0 1 0 0 1 1 0 0 0 0 0 0 1 0 0 0 0 0 0
 0 1 0 0 0 0 0 1 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 1 0 1 1 0 1 0 0 0 0 0 1 0 0
 1 0 1 0 0 1 0 1 0 0 0 0 0 0 0 0 1 1 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 1 0
 0 0 0 0 0 0 1 0 1 0 0 1 

In [ ]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 42)

In [ ]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [ ]:
print(X_train)

[[-1.44075296 -0.43531947 -1.36208497 ...  0.9320124   2.09724217
   1.88645014]
 [ 1.97409619  1.73302577  2.09167167 ...  2.6989469   1.89116053
   2.49783848]
 [-1.39998202 -1.24962228 -1.34520926 ... -0.97023893  0.59760192
   0.0578942 ]
 ...
 [ 0.04880192 -0.55500086 -0.06512547 ... -1.23903365 -0.70863864
  -1.27145475]
 [-0.03896885  0.10207345 -0.03137406 ...  1.05001236  0.43432185
   1.21336207]
 [-0.54860557  0.31327591 -0.60350155 ... -0.61102866 -0.3345212
  -0.84628745]]


In [ ]:
print(X_test)


[[-0.46649743 -0.13728933 -0.44421138 ... -0.19435087  0.17275669
   0.20372995]
 [ 1.36536344  0.49866473  1.30551088 ...  0.99177862 -0.561211
  -1.00838949]
 [ 0.38006578  0.06921974  0.40410139 ...  0.57035018 -0.10783139
  -0.20629287]
 ...
 [-0.73547237 -0.99852603 -0.74138839 ... -0.27741059 -0.3820785
  -0.32408328]
 [ 0.02898271  2.0334026   0.0274851  ... -0.49027026 -1.60905688
  -0.33137507]
 [ 1.87216885  2.80077153  1.80354992 ...  0.7925579  -0.05868885
  -0.09467243]]


In [ ]:
from sklearn.linear_model import LogisticRegression
classifier = LogisticRegression(random_state = 42)
classifier.fit(X_train, y_train)

LogisticRegression(random_state=42)

In [ ]:
print(classifier.predict(sc.transform([[11.34,18.33,75.66,567.8,0.089045,0.06553,0.1334,0.1234,0.01256,0.2556,0.07896,0.9443,0.993,9.227,0.004562,0.08668,0.1,0.0236,0.03453,0.0045612,28.4,28.03,206.7,2306,0.1701,0.6969,0.9658,0.281,0.455,0.09789]])))

[1]


In [ ]:
y_pred = classifier.predict(X_test)
print(np.concatenate((y_pred.reshape(len(y_pred), 1), y_test.reshape(len(y_test), 1)),1))

[[0 0]
 [1 1]
 [1 1]
 [0 0]
 [0 0]
 [1 1]
 [1 1]
 [1 1]
 [0 0]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [1 1]
 [0 0]
 [1 1]
 [0 0]
 [0 0]
 [0 0]
 [1 1]
 [0 1]
 [0 0]
 [1 1]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [1 1]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [1 1]
 [1 1]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [1 1]
 [1 1]
 [0 0]
 [0 0]
 [1 1]
 [1 1]
 [0 0]
 [0 0]
 [0 0]
 [1 1]
 [1 1]
 [0 0]
 [0 0]
 [1 1]
 [1 1]
 [0 0]
 [1 1]
 [0 0]
 [0 0]
 [0 0]
 [0 1]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [1 1]
 [1 1]
 [0 0]
 [1 1]
 [1 1]
 [0 0]
 [1 1]
 [1 1]
 [0 0]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [1 0]
 [1 1]]


In [ ]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred)
print(cm)
accuracy_score(y_test, y_pred)

[[70  1]
 [ 2 41]]


0.9736842105263158

In [ ]:
!pip install -q streamlit

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 8.9/8.9 MB 68.1 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 164.8/164.8 kB 19.5 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... done
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 184.3/184.3 kB 21.4 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 4.8/4.8 MB 97.9 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 82.1/82.1 kB 9.4 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 62.7/62.7 kB 7.9 MB/s eta 0:00:00


In [ ]:
%%writefile app.py

import streamlit as st

st.write('Hello, *World!* :sunglasses:')

Writing app.py


In [ ]:
!npm install localtunnel

npm WARN saveError ENOENT: no such file or directory, open '/content/package.json'
npm notice created a lockfile as package-lock.json. You should commit this file.
npm WARN enoent ENOENT: no such file or directory, open '/content/package.json'
npm WARN content No description
npm WARN content No repository field.
npm WARN content No README data
npm WARN content No license field.

+ localtunnel@2.0.2
added 22 packages from 22 contributors and audited 22 packages in 1.731s

3 packages are looking for funding
  run `npm fund` for details

found 0 vulnerabilities



In [ ]:
!streamlit run app.py &>/content/logs.txt &

In [ ]:
!npx localtunnel --port 8501 & curl ipv4.icanhazip.com

35.247.76.119
npx: installed 22 in 1.993s
your url is: https://modern-pots-train.loca.lt


In [ ]:
import streamlit as st




In [ ]:
%%writefile breastcancer.py

import streamlit as st
import pandas as pd
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score
def user_report():
  radius_mean= st.sidebar.slider('radius_mean', 0.00,25.00,3.00 )
  Texture_mean= st.sidebar.slider('Texture_mean', 0.00,30.00, 5.00 )
  perimeter_mean = st.sidebar.slider('perimeter_mean', 0.00,150.00, 70.00 )
  area_mean = st.sidebar.slider('area_mean', 0.0,1500.0,1326.00 )
  smoothness_mean = st.sidebar.slider('smoothness_mean', 0.0000000,2.0000000, 0.1000000)
  compactness_mean = st.sidebar.slider('compactness_mean', 0.00000,2.00000, 0.2130000)
  concavity_mean = st.sidebar.slider('concavity_mean', 0.0000000,2.0000000, 0.3000000 )
  concave_points_mean = st.sidebar.slider('concave points_mean', 0.0000000,2.0000000, 0.3000000 )
  symmetry_mean = st.sidebar.slider('symmetry_mean', 0.0000000,2.0000000, 0.3000000 )
  fractal_dimension_mean = st.sidebar.slider('fractal_dimension_mean', 0.000000,1.000000, 0.030000 )
  radius_se = st.sidebar.slider('radius_se', 0.000000,2.000000, 0.300000 )
  texture_se = st.sidebar.slider('texture_se', 0.000000,2.000000, 0.900000 )
  perimeter_se = st.sidebar.slider('perimeter_se', 0.0000,10.000, 8.563 )
  area_se = st.sidebar.slider('area_se', 0.00,200.00, 153.60 )
  smoothness_se = st.sidebar.slider('smoothness_se', 0.0000000,1.0000000, 0.00639000 )
  compactness_se = st.sidebar.slider('compactness_se', 0.0000000,1.0000000, 0.0345700 )
  concavity_se = st.sidebar.slider('concavity_se', 0.000000,1.000000, 0.05904 )
  concave_points_se = st.sidebar.slider('concave points_se', 0.000000,1.000000, 0.0383 )
  symmetry_se = st.sidebar.slider('symmetry_se', 0.000000,1.000000, 0.01756 )
  fractal_dimension_se = st.sidebar.slider('fractal_dimension_se', 0.000000,1.000000, 0.00619 )
  radius_worst = st.sidebar.slider('radius_worst', 0.0,70.0, 26.32 )
  texture_worst = st.sidebar.slider('texture_worst', 0.0,60.0, 30.73 )
  perimeter_worst = st.sidebar.slider('perimeter_worst', 0.0,250.0, 184.6 )
  area_worst = st.sidebar.slider('area_worst', 0.0,2500.0, 2019.3 )
  smoothness_worst = st.sidebar.slider('smoothness_worst', 0.000000,2.000000, 0.1457 )
  compactness_worst = st.sidebar.slider('compactness_worst', 0.000000,2.000000, 0.6656 )
  concavity_worst = st.sidebar.slider('concavity_worst', 0.000000,2.000000, 0.7 )
  concave_points_worst = st.sidebar.slider('concave points_worst', 0.000000,2.000000, 0.2393)
  symmetry_worst = st.sidebar.slider('symmetry_worst', 0.000000,2.000000, 0.3938 )
  fractal_dimension_worst = st.sidebar.slider('fractal_dimension_worst', 0.0000000,1.0000000, 0.0834)

  user_report_data = {
      'radius_mean':radius_mean,
      'Texture_mean':Texture_mean,
      'perimeter_mean':perimeter_mean,
      'area_mean':area_mean,
      'smoothness_mean':smoothness_mean,
      'compactness_mean':compactness_mean,
      'concavity_mean':concavity_mean,
      'concave_points_mean':concave_points_mean,
      'symmetry_mean':symmetry_mean,
      'fractal_dimension_mean':fractal_dimension_mean,
      'radius_se':radius_se,
      'texture_se':texture_se,
      'perimeter_se':perimeter_se,
      'area_se':area_se,
      'smoothness_se':smoothness_se,
      'compactness_se':compactness_se,
      'concavity_se':concavity_se,
      'concave_points_se':concave_points_se,
      'symmetry_se':symmetry_se,
      'fractal_dimension_se':fractal_dimension_se,
      'radius_worst':radius_worst,
      'texture_worst':texture_worst,
      'perimeter_worst':perimeter_worst,
      'area_worst':area_worst,
      'smoothness_worst':smoothness_worst,
      'compactness_worst':compactness_worst,
      'concavity_worst':concavity_worst,
      'concave_points_worst':concave_points_worst,
      'symmetry_worst':symmetry_worst,
      'fractal_dimension_worst':fractal_dimension_worst,

  }
  report_data = pd.DataFrame(user_report_data, index=[0])
  return report_data

read_file = pd.read_excel ("/content/maindataset.xlsx")
read_file.to_csv ("breastcancer.csv", index = None,header=True)
dataset = pd.read_csv('breastcancer.csv')
X = dataset.iloc[:, 1:-1].values
y = dataset.iloc[:, -1].values

user_data = user_report()
st.subheader('Patient Data')
st.write(user_data)

from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 42)


lr  = LogisticRegression()
lr.fit(X_train, y_train)
user_result = lr.predict(user_data)

st.subheader('Your Report: ')
output=''
if user_result[0]==1:
  output = 'You are have high risk of breast cancer'
else:
  output = 'You have low risk of breast cancer'
st.title(output)
st.subheader('Accuracy: ')
st.write(str(accuracy_score(y_test, lr.predict(X_test))*100)+'%')

Overwriting breastcancer.py


In [ ]:
!npm install localtunnel

npm WARN saveError ENOENT: no such file or directory, open '/content/package.json'
npm WARN enoent ENOENT: no such file or directory, open '/content/package.json'
npm WARN content No description
npm WARN content No repository field.
npm WARN content No README data
npm WARN content No license field.

+ localtunnel@2.0.2
updated 1 package and audited 36 packages in 0.41s

3 packages are looking for funding
  run `npm fund` for details

found 0 vulnerabilities



In [ ]:
!streamlit run breastcancer.py &>/content/logs.txt &

In [ ]:
!npx localtunnel --port 8501 & curl ipv4.icanhazip.com

35.247.76.119
npx: installed 22 in 2.394s
your url is: https://beige-spies-carry.loca.lt


/usr/local/lib/python3.10/dist-packages/sklearn/base.py:432: UserWarning: X has feature names, but LogisticRegression was fitted without feature names
  warnings.warn(
